export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  INTERNAL_ERROR: 500,
};

export const JWT_COOKIE_NAME = 'pulsepoll_token';

export const SALT_ROUNDS = 12;

export const MIN_OPTIONS_PER_QUESTION = 2;
